require: rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - bin/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Metrics/BlockLength:
  IgnoredMethods: ['context', 'describe']

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
